### ISSUE TITLE
block in fu_each_src_dest: same file 

### ISSUE THREAD

**Issue by kazikfriedrich** [andersonvom/adp-downloader#5]
Hey,

I'm having issues running the script. Here's what happens when I run it (username and password redacted):
```
$ adp-downloader
Username: <username>
Password: <password>
/usr/share/ruby/fileutils.rb:1460:in `block in fu_each_src_dest': same file: /tmp/adp-downloader-20180403-28804-1mu1rl0 and /tmp/adp-downloader-20180403-28804-1mu1rl0 (ArgumentError)
	from /usr/share/ruby/fileutils.rb:1475:in `fu_each_src_dest0'
	from /usr/share/ruby/fileutils.rb:1459:in `fu_each_src_dest'
	from /usr/share/ruby/fileutils.rb:458:in `mv'
	from /usr/local/share/gems/gems/adp-downloader-0.2.5/lib/adp-downloader/runner.rb:29:in `log_exception_to_file'
	from /usr/local/share/gems/gems/adp-downloader-0.2.5/lib/adp-downloader/runner.rb:17:in `rescue in run'
	from /usr/local/share/gems/gems/adp-downloader-0.2.5/lib/adp-downloader/runner.rb:12:in `run'
	from /usr/local/share/gems/gems/adp-downloader-0.2.5/bin/adp-downloader:6:in `<top (required)>'
	from /usr/local/bin/adp-downloader:23:in `load'
	from /usr/local/bin/adp-downloader:23:in `<main>'
```

Here's my env:
```
payslips $ cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)

payslips $ ruby -v
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

payslips $ rpm -qa | grep ruby
rubygem-rdoc-5.1.0-2.fc27.noarch
ruby-2.4.3-87.fc27.x86_64
rubypick-1.1.1-7.fc27.noarch
ruby-libs-2.4.3-87.fc27.x86_64
rubygem-did_you_mean-1.1.0-87.fc27.x86_64
ruby-irb-2.4.3-87.fc27.noarch
rubygem-json-2.1.0-102.fc27.x86_64
rubygem-bigdecimal-1.3.0-87.fc27.x86_64
rubygem-io-console-0.4.6-87.fc27.x86_64
rubygem-openssl-2.0.5-87.fc27.x86_64
rubygems-2.6.14.1-87.fc27.noarch
rubygem-psych-2.2.2-87.fc27.x86_64
ruby-devel-2.4.3-87.fc27.x86_64

payslips $ gem query --local

*** LOCAL GEMS ***

adp-downloader (0.2.5)
bigdecimal (1.3.0)
bundler (1.13.7)
bundler_ext (0.4.1)
coderay (1.1.0)
did_you_mean (1.1.0)
domain_name (0.5.20170404)
http-cookie (1.0.3)
io-console (0.4.6)
json (2.1.0)
mechanize (2.7.5)
method_source (0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.3.0)
net-http-digest_auth (1.4.1)
net-http-persistent (2.9.4)
netrc (0.11.0)
nokogiri (1.8.2)
ntlm-http (0.1.1)
openssl (2.0.5)
parallel (1.12.1, 1.3.3)
pry (0.10.4)
psych (2.2.2)
rake (12.2.1)
rdoc (5.1.0)
rubygems-update (2.7.6)
slop (3.5.0)
unf (0.1.4)
unf_ext (0.0.7.5)
webrobots (0.1.2)
```
Here are the commands that I've run before running `$ adp-downloader`
```
 $ history | egrep -i "ruby|gem"
 1003  sudo dnf  install ruby
 1010  sudo dnf install ruby-dev
 1012  sudo gem update --system
 1014  sudo dnf install gcc ruby-devel rubygems 
 1015  sudo gem install adp-downloader
 1022  sudo dnf install rubygem-json 
```

I've done some googling, but no luck
Edit:

After looking at https://rubygems.org/gems/adp-downloader I also installed the following, but the error still persist:
```
 1047  sudo dnf install rubygem-parallel.noarch rubygem-netrc.noarch rubygem-mechanize.noarch 
 1050  dnf install rubygem-rake.noarch rubygem-bundler_ext.noarch rubygem-pry.noarch
```

**Comment by andersonvom** [comment]
@kazikfriedrich The script stopped working several days ago due to a recent change in ADP. In order to submit the login form now, they require some extra parameters that are calculated at runtime in JS. I haven't figured out a way to make this work yet, but any help is appreciated! =)

See the other issue I created about this specific problem: #6
